[package]
name = "asm_docs_parsing"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
asm-lsp = {path = "../" }
clap = { version = "4.5.8", features = ["derive"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
